export const SCRATCH_CARD_FETCH_SUCCEEDED = 'SCRATCH_CARD_FETCH_SUCCEEDED';
export const SCRATCH_CARD_FETCH_FAILED = 'SCRATCH_CARD_FETCH_FAILED';
export const SCRATCH_CARD_DETAILS = 'SCRATCH_CARD_DETAILS';
export const SCRATCH_CARD_CREATED = 'SCRATCH_CARD_CREATED';
export const SCRATCH_CARD_CREATE_FAILED = 'SCRATCH_CARD_CREATE_FAILED';
export const SCRATCH_CARD_DELETED = 'SCRATCH_CARD_DELETED';
export const SCRATCH_CARD_DELETE_FAILED = 'SCRATCH_CARD_DELETE_FAILED';
export const IS_FETCHING_CARDS = 'IS_FETCHING_CARDS';
export const PRINTED_CARDS_UPDATED = 'PRINTED_CARDS_UPDATED';

export const USER_CREATED = 'USER_CREATED';
export const USER_CREATION_FAILED = 'USER_CREATION_FAILED';
export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';
export const USER_FETCH_FAILED = 'USER_FETCH_FAILED';
export const USER_LOGIN_SUCCEEDED = ' USER_LOGIN_SUCCEEDED';
export const USER_LOGIN_FAILED = ' USER_LOGIN_FAILED';
export const IS_FETCHING_USER = 'IS_FETCHING_USER';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const API_KEY_REFRESHED = 'API_KEY_REFRESHED';

